### ISSUE TITLE
Update workflow for recetox-aplcms to v0.10.3

### ISSUE THREAD

**Issue by hechth** [RECETOX/workflow-testing#13]
The recetox-aplcms tool should also contain a workflow which connects the individual steps and pipes the data in the correct way so that it is actually easier to use.

- [x] Create Galaxy workflow
- [x] Finalize workflow documentation
- [x] Upload workflow to GitHub
- [x] Publish workflow in History
- [x] Create workflow test

**Comment by xtrojak** [comment]
This should be revisited and properly finished with the new release of apLCMSv0.10.0 and the consequent update of its wrappers in [RECETOX/galaxytools#308](https://github.com/RECETOX/galaxytools/issues/308).

**Comment by xtrojak** [comment]
@hechth do we want to include the [mzml_validator](https://github.com/RECETOX/galaxytools/tree/master/tools/mzml_validator) as the first step of the workflows?

**Comment by hechth** [comment]
> @hechth do we want to include the [mzml_validator](https://github.com/RECETOX/galaxytools/tree/master/tools/mzml_validator) as the first step of the workflows?

Not at this point
