### ISSUE TITLE
Add GC MS pipeline using xcms

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/workflow-testing#20]
Create GC MS workflow that starts with `xcms`. Add it as a subdirectory in GCMS directory, alongside with the workflow using `aplcms`.

It uses the following steps:

* `msconvert` to convert raw to mzML (check `Apply peak picking`)
   * peak picking in m/z dimension - actually creates centroids
* preprocessing step using `xcms`
   * extract information from raw data to obtain a peak table
   * the result is intensity table, metadata table, and Rdata object
* `ramclustr`
   * extract mass spectra in msp format
* `riassigner`
   * assign retention indices based on given reference compound list
* `matchms`
   * find matches with given reference spectra database

**Comment by hechth** [comment]
@xtrojak The first draft is there - now we need to test it and add proper annotations for the individual steps.
