### ISSUE TITLE
Create end-to-end workflow for spectra predictions

### ISSUE THREAD

**Issue by wverastegui** [RECETOX/workflow-testing#33]
The end-to-end steps have been tested successfully in this history (https://usegalaxy.eu/u/fec10a00c58544209329288deb71ea45/h/gfn1-xtbmultimolsinsdftestopt2qcxms-1-1-1). Use it to create and document the workflow.

Steps include the following tools:
- Input in SDF format
- `Generate conformers` 
- `Compound conversion`
-  `xtb molecular optimizations` 
- `QCxMS neutral run` 
- `QCxMS production run`
- `Filter failed datasets`
- `QCxMS get results`

**Comment by hechth** [comment]
Is this already updated to all latest versions of the tools? If so, I think this can be merged?

**Comment by wverastegui** [comment]
It is still waiting for the release of updated tools on Galaxy. It can be merged now and leave the workflow update for later.  New versions of the tool only correct typos.

**Comment by hechth** [comment]
The tools should be updated by Monday so we can finish the workflow on monday.

**Comment by wverastegui** [comment]
The workflow is up to date with the new release of the tools QCxMS neutral run and QCxMS get results.
