### ISSUE TITLE
look into adopting the official planemo-ci-action

### ISSUE THREAD

**Issue by martenson** [RECETOX/workflow-testing#8]
https://github.com/galaxyproject/planemo-ci-action

**Comment by hechth** [comment]
@martenson I think this is what we use at the moment, right?

**Comment by martenson** [comment]
correct

**Comment by xtrojak** [comment]
Currently, the CI is not working. We should adopt a testing action from [here](https://github.com/galaxyproject/iwc/tree/main/.github/workflows).
